package com.gm220s.manager;

import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;import java.util.regex.*;

public class MainActivity extends Activity {
 EditText ip,user,pass; Button login,refresh; TextView status; LinearLayout devices; String base; String cookie=""; String token="";
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main); ip=findViewById(R.id.ip);user=findViewById(R.id.user);pass=findViewById(R.id.pass);login=findViewById(R.id.login);refresh=findViewById(R.id.refresh);status=findViewById(R.id.status);devices=findViewById(R.id.devices);
 login.setOnClickListener(v->login()); refresh.setOnClickListener(v->loadDevices());}
 void login(){ base="http://"+ip.getText().toString().trim(); status.setText("Logging in…"); new Thread(()->{try{String body="username="+enc(user.getText().toString())+"&password="+enc(pass.getText().toString()); Resp r=req("POST",base+"/",body,"application/x-www-form-urlencoded"); cookie=r.cookie; token=find(r.body,"(?:_SESSION_TOKEN|SESSION_TOKEN)\\s*[:=]\\s*['\"]([^'\"]+)"); ui(()->{status.setText("Login request completed");refresh.setEnabled(true);loadDevices();});}catch(Exception e){ui(()->status.setText("Login error: "+e.getMessage()));}}).start();}
 void loadDevices(){status.setText("Loading devices…");new Thread(()->{try{String url=base+"/getpage.gch?pid=1002&nextpage=net_dhcp_dynamic_t.gch";Resp r=req("GET",url,null,null);ArrayList<String[]> list=parse(r.body);ui(()->{devices.removeAllViews();status.setText("Devices found: "+list.size());for(String[] d:list)addDevice(d);});}catch(Exception e){ui(()->status.setText("Load error: "+e.getMessage()));}}).start();}
 void addDevice(String[] d){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(0,18,0,18);TextView t=new TextView(this);t.setText("Name: "+d[0]+"\nIP: "+d[1]+"\nMAC: "+d[2]);t.setTextSize(16);Button block=new Button(this);block.setText("Block / Unblock");block.setOnClickListener(v->macAction(d[2]));box.addView(t);box.addView(block);devices.addView(box);}
 void macAction(String mac){new Thread(()->{try{String body="IF_ACTION=new&SrcMacAddr="+enc(mac)+(token.isEmpty()?"":"&_SESSION_TOKEN="+enc(token));Resp r=req("POST",base+"/getpage.gch?pid=1002&nextpage=net_macfilter_maclist_t.gch",body,"application/x-www-form-urlencoded");ui(()->Toast.makeText(this,r.code==200?"Request sent":"Router returned "+r.code,Toast.LENGTH_SHORT).show());}catch(Exception e){ui(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_SHORT).show());}}).start();}
 ArrayList<String[]> parse(String s){ArrayList<String[]> out=new ArrayList<>();Matcher m=Pattern.compile("(?:([\\w ._-]{1,50})[^<]{0,300})?(?:([0-9]{1,3}(?:\\.[0-9]{1,3}){3}))[^\\n]{0,500}?([0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5})",Pattern.CASE_INSENSITIVE).matcher(s);while(m.find()){out.add(new String[]{m.group(1)==null?"Device":m.group(1).trim(),m.group(2),m.group(3)});}return out;}
 Resp req(String method,String url,String body,String type)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setDoInput(true);if(!cookie.isEmpty())c.setRequestProperty("Cookie",cookie);if(type!=null)c.setRequestProperty("Content-Type",type);if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes("UTF-8"));}}int code=c.getResponseCode();String ck=c.getHeaderField("Set-Cookie");if(ck!=null)cookie=ck.split(";",2)[0];InputStream is=code>=400?c.getErrorStream():c.getInputStream();String text="";if(is!=null){BufferedReader br=new BufferedReader(new InputStreamReader(is));StringBuilder sb=new StringBuilder();String x;while((x=br.readLine())!=null)sb.append(x).append('\n');text=sb.toString();}return new Resp(code,text,cookie);}
 String enc(String x)throws Exception{return URLEncoder.encode(x,"UTF-8");}String find(String s,String p){Matcher m=Pattern.compile(p).matcher(s);return m.find()?m.group(1):"";}void ui(Runnable r){runOnUiThread(r);}static class Resp{int code;String body,cookie;Resp(int c,String b,String k){code=c;body=b;cookie=k;}}
}
